### ISSUE TITLE
Premise of Game

### ISSUE THREAD

**Issue by resindrake** [resindrake/frontiersmen#24]
If we do eventually want to make this game into a survival game, what should the premise and lore be?

### I propose the following:
* Game is set in a frontier, such as Alaska or Yukon
* Player and NPCs move to the frontier for gold or oil operations
* Connections to the rest of North America exist, but is very remote
    * I.e. you can purchase equipment online and have it shipped, but it takes a long time to arrive
    * Perhaps you need to construct a reception tower before you can reach the rest of the world reliably?
* Game name should then be something along the lines of "Frontierplanner"

Obstacles:
* The cold
* Cave-ins
* Wild animals, esp. bears

Drawbacks:
* This would make the game focused on gold mining. This may be good, but it also prevents the player from, say, pursuing farming or mining iron
    * Unless the player is simply the one who enables miners to come in and prospect, and works as a farmer or whatever on the side
* Apart from wildlife, there isn't really much combat in the game (but maybe that's a good thing)

**Please discuss below.**

**Comment by resindrake** [comment]
Also it means we'd probably have a LOT of snow. Just, endless miserable winters that bury your house and takes forever to clear

**Comment by Krutonium** [comment]
Add "Money" to Obstacles, since you need to make it to make online orders.

As for game name, perhaps somthing that sounds a bit less Beta, like "Frontier Town"

**Comment by resindrake** [comment]
Has Frontier Town been used yet?

**Comment by Krutonium** [comment]
https://store.steampowered.com/search/?term=Frontier+Town
https://www.google.com/search?client=firefox-b-d&q=Frontier+Town+Game

Not that I'm seeing - there is a game with a Similar DLC name, and a board game that seems to have never gotten anywhere.

**Comment by resindrake** [comment]
Still wouldn't want to risk it; never know if it was created by an aggressive or jealous guy who isn't scared of getting a lawyer lol

**Comment by resindrake** [comment]
![image](https://user-images.githubusercontent.com/62374268/98764520-16886600-2430-11eb-9da4-42b12debb451.png)
Frontier Designer?

**Comment by resindrake** [comment]
Icon will see revision when derg adds S N O W

**Comment by resindrake** [comment]
Pretty sure this issue is basically settled at this point; any further worldbuilding can be discussed in separate issues
