### ISSUE TITLE
Add furniture, wallpaper

### ISSUE THREAD

**Issue by resindrake** [resindrake/frontiersmen#37]
Structural
- [ ] Door
    - [ ] Open and closed, as well as partway for animation
- [ ] Glass window
- [ ] Ladder
- [ ] Curtains
- [ ] Wallpaper
- [ ] Tiles
- [ ] Skirting

Bedroom
- [ ] Bed
- [ ] Dresser
- [ ] Dressing table
- [ ] Desk

Bathroom
- [ ] Bath
- [ ] Shower
- [ ] Bathroom Sink
- [ ] Mirror

Kitchen 
- [ ] Stove
- [ ] Kitchen Sink
- [ ] Fridge
- [ ] Lower cabinets
- [ ] Upper cabinets

Outdoors
- [ ] Campfire

**Comment by Krutonium** [comment]
Outdoor Lights

**Comment by resindrake** [comment]
Moved to #40.
